"""empty message

Revision ID: aa510789b78d
Revises: f8fede235304
Create Date: 2021-01-03 14:21:21.180537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa510789b78d'
down_revision = 'f8fede235304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holding', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holding', 'name')
    # ### end Alembic commands ###
