"""empty message

Revision ID: f8fede235304
Revises: ed9b014de0b0
Create Date: 2020-12-25 13:19:52.421549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fede235304'
down_revision = 'ed9b014de0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holding', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holding', 'current_price')
    # ### end Alembic commands ###
